version: "3"
services:
  varnish:
    container_name: varnish
    build:
      context: varnish/
    ports:
      - 6081:6081
    depends_on:
      - nginx

  redis:
    container_name: redis
    command: redis-server --appendonly no --maxmemory-policy allkeys-lru --maxmemory 500mb --loglevel verbose
    restart: always
    image: redis:latest
    hostname: redis.magento2.docker
    ports:
      - 127.0.0.1:6379:6379

  nginx:
    container_name: nginx
    build:
      context: nginx/
    working_dir: /etc/nginx
    ports:
      # {internal_in_docker}:{external_from_browser}
      - 80:80
      - 443:443
      - 8001:8001
    volumes:
      - ./magento:/var/www/magento
    env_file:
      - ./.env

  magento:
    container_name: magento
    hostname: fpm.magento2.docker
    build:
      context: php-fpm/
    image: meanbee/magento2-php:7.2-fpm
    volumes:
      - ./magento:/var/www/magento
      - ./volume/.composer:/var/www/.composer
    extra_hosts:
      - "${DOMAIN_NAME}:${LOCAL_HOST_IP}"
    env_file:
      - ./composer.env
      - ./.env
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - PHP_IDE_CONFIG=serverName=magento2.docker

  mysql:
    container_name: mysql
    image: mariadb:10
    build:
      context: ./mysql
    ports:
      - 3306:3306
    volumes:
      - ./volume/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TERM=meh

  magento_cli:
    build:
      context: php-cli/
    hostname: cli.magento2.docker
    image: meanbee/magento2-php:7.2-cli
    volumes:
      - ./volume/.composer/cache:/root/.composer/cache
      - ./magento:/var/www/magento
    env_file:
      - ./composer.env
      - ./.env

  magento_cron:
    container_name: cron
    build:
      context: php-cli/
    image: meanbee/magento2-php:7.2-cli
    hostname: magento2-cron.docker
    command: run-cron
    environment:
      - ENABLE_SENDMAIL=true
    volumes:
      - ./magento:/var/www/magento
    env_file:
      - ./composer.env
      - ./.env

  chrome:
    container_name: chrome
    image: selenium/standalone-chrome:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    extra_hosts:
      - "${DOMAIN_NAME}:${LOCAL_HOST_IP}"
