version: "2"
services:
  varnish:
    image: meanbee/magento2-varnish:latest
    environment:
      - VIRTUAL_HOST=magento2.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - 81:80
    links:
      - web

  web:
    image: meanbee/magento2-nginx:1.9
    ports:
      - 80:80
    links:
      - magento
      - mysql
    volumes_from:
      - magento
    env_file:
      - ./global.env
    #environment:
      #- VIRTUAL_HOST=magento2.docker
      #- VIRTUAL_PORT=80
      #- HTTPS_METHOD=noredirect

  magento:
    hostname: fpm.magento2.docker
    image: meanbee/magento2-php:7.1-fpm
    ports:
      - 8081:80
    links:
      - mysql
    volumes:
      - ./magento:/var/www/magento
      - ./volume/.composer:/var/www/.composer
    env_file:
      - ./global.env

  mysql:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./volume/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - TERM=meh

  magento_cli:
    hostname: cli.magento2.docker
    image: meanbee/magento2-php:7.1-cli
    links:
      - mysql
    volumes:
      - ./volume/.composer/cache:/root/.composer/cache
    volumes_from:
      - magento
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_DB_HOST=mysql
      - M2SETUP_DB_NAME=magento2
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - M2SETUP_BASE_URL=http://magento2.docker/
      # - M2SETUP_SECURE_BASE_URL=https://magento2.docker/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=admin123
      - M2SETUP_VERSION=2.2.*
      # - M2SETUP_USE_SAMPLE_DATA=true

  magento_cron:
    image: meanbee/magento2-php:7.1-cli
    hostname: magento2-cron.docker
    command: run-cron
    env_file:
      - ./global.env    
    environment:
      - ENABLE_SENDMAIL=true
    volumes_from:
      - magento
    links:
      - mysql
